[versions]
# kotlin
coroutines = "1.10.2"

# databases
sqlite = "3.51.1.0"

# third party
okhttp = "5.3.2"
gson = "2.13.2"

[libraries]
# kotlin
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}

# databases
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite"}

# third party
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }